version: "2"
run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - unused
    - goimports
    - misspell
    - unconvert
    - nakedret
    - gocyclo
    - dupl
    - goconst
    - gocritic

issues:
  max-same-issues: 0   
  max-issues-per-linter: 0 