services:
  db:
    image: postgres:17
    container_name: avito_pvz_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - avito_pvz_network
    env_file:
      - .env
  migrate:
    image: ghcr.io/kukymbr/goose-docker:latest
    container_name: avito_pvz_migrate
    environment:
      GOOSE_DRIVER: ${DB_PROTOCOL}
      GOOSE_DBSTRING: "host=${DB_HOST} port=${DB_PORT} user=${DB_USER} dbname=${DB_NAME} password=${DB_PASSWORD} ${DB_OPTIONS}"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    networks:
      - avito_pvz_network
    env_file:
      - .env

networks:
  avito_pvz_network:
    driver: bridge

volumes:
  db_data: