services:
  db:
    image: postgres:17
    container_name: avito_pvz_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - avito_pvz_network
    env_file:
      - .env
  migrate:
    image: ghcr.io/kukymbr/goose-docker:latest
    container_name: avito_pvz_migrate
    environment:
      GOOSE_DRIVER: ${DB_PROTOCOL}
      GOOSE_DBSTRING: "host=${DB_HOST} port=${DB_PORT} user=${DB_USER} dbname=${DB_NAME} password=${DB_PASSWORD} ${DB_OPTIONS}"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    networks:
      - avito_pvz_network
    env_file:
      - .env
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avito_pvz_app
    environment:
      TIMEOUT: ${TIMEOUT}
      IDLE_TIMEOUT: ${IDLE_TIMEOUT}
      HTTP_SERVER_PORT: ${HTTP_SERVER_PORT}
      SIGNING_KEY: ${SIGNING_KEY}
      DB_PROTOCOL: ${DB_PROTOCOL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_OPTIONS: ${DB_OPTIONS}
      DEFAULT_PAGE: ${DEFAULT_PAGE}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
      GRPC_SERVER_PORT: ${GRPC_SERVER_PORT}
      INTERNAL_PROMETHEUS_PORT: ${INTERNAL_PROMETHEUS_PORT}
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:3000:3000"
    expose:
      - "9090"
    depends_on:
      migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    networks:
      - avito_pvz_network
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9000:9090"
    networks:
      - avito_pvz_network
      
networks:
  avito_pvz_network:
    driver: bridge

volumes:
  db_data: