global:
  scrape_interval: "15s"
  scrape_timeout: "15s"
  evaluation_interval: "1m"

scrape_configs:
  - job_name: 'avito_pvz_api'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'app:9090'  